#!/bin/bash

VENV_DIR="venv"
PORT=${1:-8080}

if [ ! -d "$VENV_DIR" ]; then
    echo "Virtual environment not found. Creating one..."
    python3 -m venv $VENV_DIR
    $VENV_DIR/bin/pip install -r requirements.txt
fi

$VENV_DIR/bin/python main.py "$PORT"
